name: Branch

on:
  - push

jobs:
  deploy:
    strategy:
      matrix:
        target_env: [stg, prod]
        include:
          - target_env: stg
            key: 123
          - target_env: prod
            key: 456
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 15
      - run: |
          node --version
          npm --version
          yarn --version
      - run: echo ${{ matrix.target_env }}
      - run: echo ${{ matrix.key }}
      - run: npx @mstssk/whatver node
      - name: Store zip
        uses: actions/upload-artifact@v2
        with:
          name: test
          path: .github
