name: Branch

on:
  - push

jobs:
  build:
    concurrency: ci-${{ github.ref }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [20, 22]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - run: echo $GITHUB_REF_NAME
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Show versions
        run: |
          node --version
          npm --version
          yarn --version
      - run: npx @mstssk/whatver node
      - name: Store zip
        uses: actions/upload-artifact@v4
        with:
          name: test
          path: .github
