name: Tags

on:
  push:
    tags: ["v**"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo TAGS
      - run: "echo ${GITHUB_REF#refs/*/}"
      - name: Set env
        run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF#refs/*/}
      - run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Show versions
        run: |
          node --version
          npm --version
          yarn --version
      - run: "zip release.zip ./README.md"
      - run: ls
      - name: Store zip
        uses: actions/upload-artifact@v2
        with:
          name: "release_${RELEASE_VERSION}"
          path: release.zip
